# Generated by Django 5.2 on 2025-06-26 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_gender_alter_customuser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='code',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
