# Generated by Django 5.2 on 2025-05-03 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_customuser_blood_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
