# Generated by Django 5.2 on 2025-06-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_department_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.IntegerField(unique=True),
        ),
    ]
