# Generated by Django 5.2 on 2025-07-02 17:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_otp_otp_otp_code_otp_is_verified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('session_id', models.UUIDField(default=uuid.uuid4)),
            ],
        ),
    ]
