# Generated by Django 5.2.4 on 2025-07-20 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_emaillink'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_eligible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
