# Generated by Django 5.2.4 on 2025-08-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_customuser_is_eligible_customuser_is_rejected'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_form', models.CharField(max_length=20)),
                ('code', models.IntegerField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
