# Generated by Django 5.2 on 2025-05-09 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_customuser_date_of_birth_customuser_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_photo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
